services:
  app:
    build: ./app
    container_name: movieflix-app
    environment:
      - FLASK_ENV=production
    expose:
      - '5000'
    volumes:
      - ./app:/app
      - /home/andre/Downloads:/downloads
      - ./etl:/app/etl
    depends_on:
      - db
    networks:
      - movieflix

  nginx:
    image: nginx:alpine
    container_name: movieflix-nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - movieflix

  db:
    image: postgres:15-alpine
    container_name: movieflix-postgres
    environment:
      POSTGRES_USER: movieflix
      POSTGRES_PASSWORD: movieflix
      POSTGRES_DB: movieflix_dw
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - movieflix

volumes:
  db_data:

networks:
  movieflix:
    driver: bridge
